/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Each step reads a CSS variable, so switching theme or accent
        // rewrites the variables in index.css and every existing
        // className keeps working.
        white: 'rgb(var(--c-white) / <alpha-value>)',
        primary: {
          50: 'rgb(var(--c-primary-50) / <alpha-value>)',
          100: 'rgb(var(--c-primary-100) / <alpha-value>)',
          200: 'rgb(var(--c-primary-200) / <alpha-value>)',
          300: 'rgb(var(--c-primary-300) / <alpha-value>)',
          400: 'rgb(var(--c-primary-400) / <alpha-value>)',
          500: 'rgb(var(--c-primary-500) / <alpha-value>)',
          600: 'rgb(var(--c-primary-600) / <alpha-value>)',
          700: 'rgb(var(--c-primary-700) / <alpha-value>)',
          800: 'rgb(var(--c-primary-800) / <alpha-value>)',
          900: 'rgb(var(--c-primary-900) / <alpha-value>)',
          950: 'rgb(var(--c-primary-950) / <alpha-value>)',
        },
        accent: {
          50: 'rgb(var(--c-accent-50) / <alpha-value>)',
          100: 'rgb(var(--c-accent-100) / <alpha-value>)',
          200: 'rgb(var(--c-accent-200) / <alpha-value>)',
          300: 'rgb(var(--c-accent-300) / <alpha-value>)',
          400: 'rgb(var(--c-accent-400) / <alpha-value>)',
          500: 'rgb(var(--c-accent-500) / <alpha-value>)',
          600: 'rgb(var(--c-accent-600) / <alpha-value>)',
          700: 'rgb(var(--c-accent-700) / <alpha-value>)',
          800: 'rgb(var(--c-accent-800) / <alpha-value>)',
          900: 'rgb(var(--c-accent-900) / <alpha-value>)',
        },
        success: {
          50: 'rgb(var(--c-success-50) / <alpha-value>)',
          100: 'rgb(var(--c-success-100) / <alpha-value>)',
          200: 'rgb(var(--c-success-200) / <alpha-value>)',
          300: 'rgb(var(--c-success-300) / <alpha-value>)',
          400: 'rgb(var(--c-success-400) / <alpha-value>)',
          500: 'rgb(var(--c-success-500) / <alpha-value>)',
          600: 'rgb(var(--c-success-600) / <alpha-value>)',
          700: 'rgb(var(--c-success-700) / <alpha-value>)',
          800: 'rgb(var(--c-success-800) / <alpha-value>)',
          900: 'rgb(var(--c-success-900) / <alpha-value>)',
        },
        warning: {
          50: 'rgb(var(--c-warning-50) / <alpha-value>)',
          100: 'rgb(var(--c-warning-100) / <alpha-value>)',
          200: 'rgb(var(--c-warning-200) / <alpha-value>)',
          300: 'rgb(var(--c-warning-300) / <alpha-value>)',
          400: 'rgb(var(--c-warning-400) / <alpha-value>)',
          500: 'rgb(var(--c-warning-500) / <alpha-value>)',
          600: 'rgb(var(--c-warning-600) / <alpha-value>)',
          700: 'rgb(var(--c-warning-700) / <alpha-value>)',
          800: 'rgb(var(--c-warning-800) / <alpha-value>)',
          900: 'rgb(var(--c-warning-900) / <alpha-value>)',
        },
        error: {
          50: 'rgb(var(--c-error-50) / <alpha-value>)',
          100: 'rgb(var(--c-error-100) / <alpha-value>)',
          200: 'rgb(var(--c-error-200) / <alpha-value>)',
          300: 'rgb(var(--c-error-300) / <alpha-value>)',
          400: 'rgb(var(--c-error-400) / <alpha-value>)',
          500: 'rgb(var(--c-error-500) / <alpha-value>)',
          600: 'rgb(var(--c-error-600) / <alpha-value>)',
          700: 'rgb(var(--c-error-700) / <alpha-value>)',
          800: 'rgb(var(--c-error-800) / <alpha-value>)',
          900: 'rgb(var(--c-error-900) / <alpha-value>)',
        },
        dark: {
          50: 'rgb(var(--c-dark-50) / <alpha-value>)',
          100: 'rgb(var(--c-dark-100) / <alpha-value>)',
          200: 'rgb(var(--c-dark-200) / <alpha-value>)',
          300: 'rgb(var(--c-dark-300) / <alpha-value>)',
          400: 'rgb(var(--c-dark-400) / <alpha-value>)',
          500: 'rgb(var(--c-dark-500) / <alpha-value>)',
          600: 'rgb(var(--c-dark-600) / <alpha-value>)',
          700: 'rgb(var(--c-dark-700) / <alpha-value>)',
          800: 'rgb(var(--c-dark-800) / <alpha-value>)',
          900: 'rgb(var(--c-dark-900) / <alpha-value>)',
          950: 'rgb(var(--c-dark-950) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'slide-right': 'slideRight 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'pulse-slow': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideRight: {
          '0%': { opacity: '0', transform: 'translateX(-10px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
      },
    },
  },
  plugins: [],
};
